version: '3.8'

services:
  backend:
    container_name: backend
    build: ./backend
    image: whatheure-backend
    ports:
      - "8888:8888"
    env_file:
      - ./backend/.env

  frontend:
    container_name: frontend
    build: ./frontend
    image: whatheure-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"

  proxy:
    container_name: nginx
    image: nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

volumes:
  db-data:
  db-config:
