version: '3.8'
services:
  backend:
    container_name: backend
    build: ./backend
    image: whatheure-backend
    ports:
      - "8888:8888"
    env_file:
      - ./backend/.env
  frontend:
    container_name: frontend
    build: ./frontend
    image: whatheure-frontend
    depends_on:
      - backend
    ports:
      - "80:5173"
  database:
    container_name: database
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Pa$$w0rd
      - MYSQL_DATABASE=whatheure
      - MYSQL_USER=whatheure
      - MYSQL_PASSWORD=Pa$$w0rd
    volumes:
      - ./db:/docker-entrypoint-initdb.d